import './global.css';
import { UiLayout } from '@/components/ui/ui-layout';
import { ClusterProvider } from '@/components/cluster/cluster-data-access';
import { SolanaProvider } from '@/components/solana/solana-provider';
import { Provider } from './provider';
import { FeePayerProvider } from '@/components/fee-payer/fee-payer.provider';

export const metadata = {
  title: 'recovery tool',
  description: 'Generated by create-solana-dapp',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <ClusterProvider>
            <FeePayerProvider>
              <SolanaProvider>
                <UiLayout>{children}</UiLayout>
              </SolanaProvider>
            </FeePayerProvider>
          </ClusterProvider>
        </Provider>
      </body>
    </html>
  );
}
