import { ClusterProvider } from '@/components/cluster/cluster-data-access';
import { CompromisedProvider } from '@/components/compromised/compromised.provider';
import { FeePayerProvider } from '@/components/fee-payer/fee-payer.provider';
import { TokensProvider } from '@/components/tokens/tokens-provider';
import { UiLayout } from '@/components/ui/ui-layout';
import './global.css';
import { Provider } from './provider';

export const metadata = {
  title: 'recovery tool',
  description: 'Generated by create-solana-dapp',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        <Provider>
          <ClusterProvider>
            <TokensProvider>
              <FeePayerProvider>
                <CompromisedProvider>
                  <UiLayout>{children}</UiLayout>
                </CompromisedProvider>
              </FeePayerProvider>
            </TokensProvider>
          </ClusterProvider>
        </Provider>
      </body>
    </html>
  );
}
